// constants.js

const MODEL_OPTIONS = [
  { value: "openrouter/auto", label: "Auto" },
  { value: "openrouter/free", label: "OpenRouter Free Router" },
  {
    value: "meta-llama/llama-4-maverick:free",
    label: "Llama 4 Maverick (free)",
  },
  { value: "meta-llama/llama-4-scout:free", label: "Llama 4 Scout (free)" },
  {
    value: "meta-llama/llama-3.1-8b-instruct:free",
    label: "Llama 3.1 8B (free)",
  },
  {
    value: "mistralai/mistral-small-3.1-24b-instruct:free",
    label: "Mistral Small 24B (free)",
  },
  { value: "google/gemma-3-12b-it:free", label: "Gemma 3 12B (free)" },
  { value: "deepseek/deepseek-chat-v3-0324:free", label: "DeepSeek V3 (free)" },
  { value: "deepseek/deepseek-r1", label: "DeepSeek R1" },
  { value: "deepseek/deepseek-r1:free", label: "DeepSeek R1 (free)" },
  {
    value: "nousresearch/hermes-3-llama-3.1-405b:free",
    label: "Hermes 3 Llama 3.1 405B (free)",
  },
  { value: "stepfun/step-3.5-flash:free", label: "StepFun Flash (free)" },
  {
    value: "cognitivecomputations/dolphin-mistral-24b-venice-edition:free",
    label: "Dolphin Mistral 24B Venice Edition (free)",
  },
  {
    value: "arcee-ai/trinity-large-preview:free",
    label: "Trinity Large Preview (free)",
  },
];

const ICONS = {
  duplicate:
    '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"></rect><rect x="2" y="2" width="13" height="13" rx="2" ry="2"></rect></svg>',
  fork: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><circle cx="12" cy="18" r="3"></circle><circle cx="6" cy="6" r="3"></circle><circle cx="18" cy="6" r="3"></circle><path d="M18 9a9 9 0 0 1-9 9"></path><path d="M6 9a9 9 0 0 0 9 9"></path></svg>',
  edit: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M18 2l4 4-8 8H10v-4l8-8z"></path><path d="M14 6l-2 2"></path><path d="M2 22h8"></path></svg>',
  delete:
    '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M3 6h18"></path><path d="M19 6v14c0 1-1 2-2 2H7c-1 0-2-1-2-2V6"></path><path d="M8 6V4c0-1 1-2 2-2h4c1 0 2 1 2 2v2"></path><path d="M10 11v6"></path><path d="M14 11v6"></path></svg>',
  regenerate:
    '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M21 12a9 9 0 0 0-9-9 9.75 9.75 0 0 0-6.74 2.74L3 8"></path><path d="M3 3v5h5"></path><path d="M3 8a9 9 0 0 0 9 9 9.75 9.75 0 0 0 6.74-2.74L21 16"></path><path d="M16 16h5v5"></path></svg>',
  copy: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"></rect><rect x="2" y="2" width="13" height="13" rx="2" ry="2"></rect></svg>',
  plus: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M12 5v14"></path><path d="M5 12h14"></path></svg>',
  speaker:
    '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><polygon points="11 5 6 9 2 9 2 15 6 15 11 19 11 5"></polygon><path d="M15.54 8.46a5 5 0 0 1 0 7.07"></path><path d="M19.07 4.93a10 10 0 0 1 0 14.14"></path></svg>',
  brain:
    '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M9.5 2A2 2 0 0 1 11 4c.94.66 1.94 1.13 3 1.33V7l2 2v2.5a12 12 0 0 1-5.5 9.5A12 12 0 0 1 1 14.5a12 12 0 0 1 5.5-9.5V9.5L9.5 7V5a2 2 0 0 1 1.5-1.94"></path><path d="M14.5 2a2 2 0 0 0 1.5 1.94V7L13.5 9.5V14.5a12 12 0 0 0 5.5 9.5 12 12 0 0 0 0-19 12 12 0 0 0-5.5 9.5V16l-2-2V9.33c1.06-.2 2.06-.67 3-1.33A2 2 0 0 0 14.5 2"></path></svg>',
  stop: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="6" y="6" width="12" height="12" rx="2"></rect></svg>',
  mic: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M12 2a3 3 0 0 0-3 3v7a3 3 0 0 0 6 0V5a3 3 0 0 0-3-3z"></path><path d="M19 10v2a7 7 0 0 1-14 0v-2"></path><line x1="12" y1="19" x2="12" y2="22"></line></svg>',
  micFilled: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M12 2a3 3 0 0 0-3 3v7a3 3 0 0 0 6 0V5a3 3 0 0 0-3-3z"></path><path d="M19 10v2a7 7 0 0 1-14 0v-2"></path><line x1="12" y1="19" x2="12" y2="22"></line></svg>',
  info: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><circle cx="12" cy="12" r="10"></circle><path d="M12 16v-4"></path><path d="M12 8h.01"></path></svg>',
  context:
    '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M14 9a2 2 0 0 1-2 2H6l-4 4V4c0-1.1.9-2 2-2h8a2 2 0 0 1 2 2v5z"></path><path d="M18 9h2a2 2 0 0 1 2 2v4l-4 4v-5c0-1.1-.9-2-2-2h-2"></path></svg>',
  ooc: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z"></path><path d="M8 10h8"></path><line x1="8" y1="14" x2="12" y2="14"></line></svg>',
  model:
    '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="3" y="11" width="18" height="10" rx="2"></rect><circle cx="12" cy="5" r="2"></circle><path d="M12 7v4"></path><line x1="8" y1="16" x2="8" y2="16"></line><line x1="16" y1="16" x2="16" y2="16"></line></svg>',
  star: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2"></polygon></svg>',
  starFilled:
    '<svg viewBox="0 0 24 24" fill="currentColor" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2"></polygon></svg>',
  badge:
    '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><circle cx="12" cy="8" r="6"></circle><path d="M15.477 12.89L17 22l-5-3-5 3 1.523-9.11"></path></svg>',
  export:
    '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"></path><polyline points="7 10 12 15 17 10"></polyline><line x1="12" y1="15" x2="12" y2="3"></line></svg>',
  import:
    '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"></path><polyline points="17 8 12 3 7 8"></polyline><line x1="12" y1="3" x2="12" y2="15"></line></svg>',
  pin: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><line x1="12" y1="17" x2="12" y2="22"></line><path d="M5 17h14v-1.76a2 2 0 0 0-1.11-1.79l-1.78-.9A2 2 0 0 1 15 10.76V6h1a2 2 0 0 0 0-4H8a2 2 0 0 0 0 4h1v4.76a2 2 0 0 1-1.11 1.79l-1.78.9A2 2 0 0 0 5 15.24Z"></path></svg>',
  pinFilled:
    '<svg viewBox="0 0 24 24" fill="currentColor" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><line x1="12" y1="17" x2="12" y2="22"></line><path d="M5 17h14v-1.76a2 2 0 0 0-1.11-1.79l-1.78-.9A2 2 0 0 1 15 10.76V6h1a2 2 0 0 0 0-4H8a2 2 0 0 0 0 4h1v4.76a2 2 0 0 1-1.11 1.79l-1.78.9A2 2 0 0 0 5 15.24Z"></path></svg>',
  settings:
    '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><circle cx="12" cy="12" r="3"></circle><path d="M19.4 15a1.65 1.65 0 0 0 .33 1.82l.06.06a2 2 0 0 1 0 2.83 2 2 0 0 1-2.83 0l-.06-.06a1.65 1.65 0 0 0-1.82-.33 1.65 1.65 0 0 0-1 1.51V21a2 2 0 0 1-2 2 2 2 0 0 1-2-2v-.09A1.65 1.65 0 0 0 9 19.4a1.65 1.65 0 0 0-1.82.33l-.06.06a2 2 0 0 1-2.83 0 2 2 0 0 1 0-2.83l.06-.06a1.65 1.65 0 0 0 .33-1.82 1.65 1.65 0 0 0-1.51-1H3a2 2 0 0 1-2-2 2 2 0 0 1 2-2h.09A1.65 1.65 0 0 0 4.6 9a1.65 1.65 0 0 0-.33-1.82l-.06-.06a2 2 0 0 1 0-2.83 2 2 0 0 1 2.83 0l.06.06a1.65 1.65 0 0 0 1.82.33H9a1.65 1.65 0 0 0 1-1.51V3a2 2 0 0 1 2-2 2 2 0 0 1 2 2v.09a1.65 1.65 0 0 0 1 1.51 1.65 1.65 0 0 0 1.82-.33l.06-.06a2 2 0 0 1 2.83 0 2 2 0 0 1 0 2.83l-.06.06a1.65 1.65 0 0 0-.33 1.82V9a1.65 1.65 0 0 0 1.51 1H21a2 2 0 0 1 2 2 2 2 0 0 1-2 2h-.09a1.65 1.65 0 0 0-1.51 1z"></path></svg>',
  user:
    '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"></path><circle cx="12" cy="7" r="4"></circle></svg>',
  book:
    '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M4 19.5A2.5 2.5 0 0 1 6.5 17H20"></path><path d="M6.5 2H20v20H6.5A2.5 2.5 0 0 1 4 19.5v-15A2.5 2.5 0 0 1 6.5 2z"></path></svg>',
  keyboard:
    '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="2" y="4" width="20" height="16" rx="2" ry="2"></rect><path d="M6 8h.001"></path><path d="M10 8h.001"></path><path d="M14 8h.001"></path><path d="M18 8h.001"></path><path d="M6 12h.001"></path><path d="M10 12h.001"></path><path d="M14 12h.001"></path><path d="M18 12h.001"></path><path d="M7 16h10"></path></svg>',
  tag:
    '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M20.59 13.41l-7.17 7.17a2 2 0 0 1-2.83 0L2 12V2h10l8.59 8.59a2 2 0 0 1 0 2.82z"></path><line x1="7" y1="7" x2="7.01" y2="7"></line></svg>',
  database:
    '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><ellipse cx="12" cy="5" rx="9" ry="3"></ellipse><path d="M21 12c0 1.66-4 3-9 3s-9-1.34-9-3"></path><path d="M3 5v14c0 1.66 4 3 9 3s9-1.34 9-3V5"></path></svg>',
  folder:
    '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M22 19a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h5l2 3h9a2 2 0 0 1 2 2z"></path></svg>',
  help:
    '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><circle cx="12" cy="12" r="10"></circle><path d="M9.09 9a3 3 0 0 1 5.83 1c0 2-3 3-3 3"></path><line x1="12" y1="17" x2="12.01" y2="17"></line></svg>',
  reload:
    '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M21 12a9 9 0 0 0-9-9 9.75 9.75 0 0 0-6.74 2.74L3 8"></path><path d="M3 3v5h5"></path><path d="M3 8a9 9 0 0 0 9 9 9.75 9.75 0 0 0 6.74-2.74L21 16"></path><path d="M16 16h5v5"></path></svg>',
  sortAsc:
    '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M3 8h14"></path><path d="M7 4v4"></path><path d="M11 4v4"></path><path d="M15 4v4"></path></svg>',
  sortDesc:
    '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M3 16h14"></path><path d="M7 20v-4"></path><path d="M11 20v-4"></path><path d="M15 20v-4"></path></svg>',
  x:
    '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><line x1="18" y1="6" x2="6" y2="18"></line><line x1="6" y1="6" x2="18" y2="18"></line></svg>',
  filter:
    '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><polygon points="22 3 2 3 10 12.46 10 19 14 21 14 12.46 22 3"></polygon></svg>',
  writing:
    '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M12 19l7-7 3 3-7 7-3-3z"></path><path d="M18 13l-1.5-7.5L2 2l3.5 14.5L13 18l5-5z"></path><path d="M2 2l7.586 7.586"></path><circle cx="11" cy="11" r="2"></circle></svg>',
  arrowUp:
    '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><line x1="12" y1="19" x2="12" y2="5"></line><polyline points="5 12 12 5 19 12"></polyline></svg>',
  arrowDown:
    '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><line x1="12" y1="5" x2="12" y2="19"></line><polyline points="19 12 12 19 5 12"></polyline></svg>',
  sort:
    '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M3 6h18"></path><path d="M6 12h12"></path><path d="M9 18h6"></path></svg>',
  calendar:
    '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="3" y="4" width="18" height="18" rx="2" ry="2"></rect><line x1="16" y1="2" x2="16" y2="6"></line><line x1="8" y1="2" x2="8" y2="6"></line><line x1="3" y1="10" x2="21" y2="10"></line></svg>',
  clock:
    '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><circle cx="12" cy="12" r="10"></circle><polyline points="12 6 12 12 16 14"></polyline></svg>',
  messages:
    '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M14 9a2 2 0 0 1-2 2H6l-4 4V4c0-1.1.9-2 2-2h8a2 2 0 0 1 2 2v5z"></path><path d="M18 9h2a2 2 0 0 1 2 2v4l-4 4v-5c0-1.1-.9-2-2-2h-1"></path></svg>',
  text:
    '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><polyline points="4 7 4 4 20 4 20 7"></polyline><line x1="9" y1="20" x2="15" y2="20"></line><line x1="12" y1="4" x2="12" y2="20"></line></svg>',
};

if (typeof window !== "undefined") {
  window.ICONS = ICONS;
}

const PROMPT_COMMAND_HISTORY_KEY = "rp-prompt-command-history";
const PROMPT_COMMAND_HISTORY_MAX = 200;
const PROMPT_HISTORY_KEY = "rp-prompt-history";
const PROMPT_HISTORY_MAX = 200;

const DEFAULT_PERSONA_COLOR = "#7c5cff";
const DEFAULT_CHAT_OPACITY = 1;
const DEFAULT_THREAD_TINT_INPUT_COLOR = "#7c5cff";

const CHARACTER_PAGE_SIZES = [0, 5, 10, 20, 50];
const CHARACTER_PAGE_BUTTON_WINDOW = 7;

const USER_INPUT_AUTO_EXPAND_MAX_HEIGHT = 280;

const DEFAULT_KOKORO_VOICE = "af_heart";
const KOKORO_MODEL_ID = "onnx-community/Kokoro-82M-v1.0-ONNX";

const KOKORO_MODULE_PATHS = [
  "https://cdn.jsdelivr.net/npm/kokoro-js@1.2.1/dist/kokoro.web.js",
];

const KOKORO_DEVICE_OPTIONS = ["wasm", "webgpu"];
const KOKORO_DTYPE_OPTIONS = [
  "fp16",
  "q8",
  "q4",
  "q4f16",
  "q8f16",
  "auto",
  "uint8",
  "uint8f16",
];
const KOKORO_DTYPE_LABELS = {
  fp16: "FP16",
  q8: "Q8",
  q4: "Q4",
  q4f16: "Q4f16",
  q8f16: "Q8f16",
  auto: "AUTO",
  uint8: "UINT8",
  uint8f16: "UINT8F16",
};
const KOKORO_VOICE_OPTIONS = [
  "af_alloy",
  "af_aoede",
  "af_bella",
  "af_heart",
  "af_jessica",
  "af_kore",
  "af_nicole",
  "af_nova",
  "af_river",
  "af_sarah",
  "af_sky",
  "am_adam",
  "am_echo",
  "am_eric",
  "am_fenrir",
  "am_liam",
  "am_michael",
  "am_onyx",
  "am_puck",
  "am_santa",
  "bf_alice",
  "bf_emma",
  "bf_isabella",
  "bf_lily",
  "bm_daniel",
  "bm_fable",
  "bm_george",
  "bm_lewis",
  "ef_dora",
  "em_alex",
  "em_santa",
  "ff_siwis",
  "hf_alpha",
  "hf_beta",
  "hm_omega",
  "hm_psi",
  "if_sara",
  "im_nicola",
  "jf_alpha",
  "jf_gongitsune",
  "jf_nezumi",
  "jf_tebukuro",
  "jm_kumo",
  "pf_dora",
  "pm_alex",
  "pm_santa",
  "zf_xiaobei",
  "zf_xiaoni",
  "zf_xiaoxiao",
  "zf_xiaoyi",
  "zm_yunjian",
  "zm_yunxi",
  "zm_yunxia",
  "zm_yunyang",
];

const KOKORO_LANGUAGE_VOICE_PREFIXES = {
  en: ["af", "am", "bf", "bm"],
  fr: ["ff"],
  it: ["if", "im"],
  ja: ["jf", "jm"],
  zh: ["zf", "zm"],
  hi: ["hf", "hm"],
  "pt-BR": ["pf", "pm"],
  pt: ["pf", "pm"],
};

const UI_LANG_OPTIONS = ["en", "fr", "it", "de", "es", "pt-BR"];
const LOCALES_BASE_PATH = "locales";
const BOT_LANGUAGE_OPTIONS = [
  "en",
  "fr",
  "it",
  "de",
  "es",
  "pt-BR",
  "pt-PT",
  "ja",
  "ko",
  "zh-CN",
  "zh-TW",
  "ru",
  "ar",
  "nl",
  "tr",
  "pl",
  "sv",
  "da",
  "fi",
  "no",
  "cs",
  "ro",
  "hu",
  "el",
  "he",
  "hi",
  "id",
  "th",
  "vi",
];

const BOT_LANGUAGE_FLAGS = {
  en: "ðŸ‡ºðŸ‡¸",
  fr: "ðŸ‡«ðŸ‡·",
  it: "ðŸ‡®ðŸ‡¹",
  de: "ðŸ‡©ðŸ‡ª",
  es: "ðŸ‡ªðŸ‡¸",
  "pt-BR": "ðŸ‡§ðŸ‡·",
  "pt-PT": "ðŸ‡µðŸ‡¹",
  ja: "ðŸ‡¯ðŸ‡µ",
  ko: "ðŸ‡°ðŸ‡·",
  "zh-CN": "ðŸ‡¨ðŸ‡³",
  "zh-TW": "ðŸ‡¹ðŸ‡¼",
  ru: "ðŸ‡·ðŸ‡º",
  ar: "ðŸ‡¸ðŸ‡¦",
  nl: "ðŸ‡³ðŸ‡±",
  tr: "ðŸ‡¹ðŸ‡·",
  pl: "ðŸ‡µðŸ‡±",
  sv: "ðŸ‡¸ðŸ‡ª",
  da: "ðŸ‡©ðŸ‡°",
  fi: "ðŸ‡«ðŸ‡®",
  no: "ðŸ‡³ðŸ‡´",
  cs: "ðŸ‡¨ðŸ‡¿",
  ro: "ðŸ‡·ðŸ‡´",
  hu: "ðŸ‡­ðŸ‡º",
  el: "ðŸ‡¬ðŸ‡·",
  he: "ðŸ‡®ðŸ‡±",
  hi: "ðŸ‡®ðŸ‡³",
  id: "ðŸ‡®ðŸ‡©",
  th: "ðŸ‡¹ðŸ‡­",
  vi: "ðŸ‡»ðŸ‡³",
};

const CHARACTER_SORT_BASES = ["created", "updated", "name", "threads"];
const CHARACTER_SORT_ICON_TEMPLATES = {
  created:
    '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32" fill="none" stroke="%231c2737" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><rect x="4" y="6" width="24" height="20" rx="2"></rect><path d="M4 12h24"></path><path d="M10 4v6"></path><path d="M22 4v6"></path></svg>',
  updated:
    '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32" fill="none" stroke="%231c2737" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="M16 8l3 5h5l-4 3 2 5-6-3-6 3 2-5-4-3h5z"></path></svg>',
  name: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32" fill="none" stroke="%231c2737" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="M8 8l3-2h10l3 2"></path><path d="M8 14h16"></path><path d="M8 20h12"></path></svg>',
  threads:
    '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32" fill="none" stroke="%231c2737" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="M4 8l3 2-3 2v4l3-2-3 2v4l3-2-3 2"></path><path d="M20 8v16"></path><path d="M14 8v16"></path></svg>',
};
const CHARACTER_SORT_LABEL_KEYS = {
  created: "characterSortCreationDate",
  updated: "characterSortUpdateDate",
  name: "characterSortName",
  threads: "characterSortChats",
};

const BOT_LANGUAGE_FLAG_ICON_CODES = {
  en: "us",
  fr: "fr",
  it: "it",
  de: "de",
  es: "es",
  "pt-BR": "br",
  "pt-PT": "pt",
  ja: "jp",
  ko: "kr",
  "zh-CN": "cn",
  "zh-TW": "tw",
  ru: "ru",
  ar: "sa",
  nl: "nl",
  tr: "tr",
  pl: "pl",
  sv: "se",
  da: "dk",
  fi: "fi",
  no: "no",
  cs: "cz",
  ro: "ro",
  hu: "hu",
  el: "gr",
  he: "il",
  hi: "in",
  id: "id",
  th: "th",
  vi: "vi",
};

const BOT_LANGUAGE_NAMES = {
  en: "English",
  fr: "French",
  it: "Italian",
  de: "German",
  es: "Spanish",
  "pt-BR": "Portuguese (Brazil)",
  "pt-PT": "Portuguese (Portugal)",
  ja: "Japanese",
  ko: "Korean",
  "zh-CN": "Chinese (Simplified)",
  "zh-TW": "Chinese (Traditional)",
  ru: "Russian",
  ar: "Arabic",
  nl: "Dutch",
  tr: "Turkish",
  pl: "Polish",
  sv: "Swedish",
  da: "Danish",
  fi: "Finnish",
  no: "Norwegian",
  cs: "Czech",
  ro: "Romanian",
  hu: "Hungarian",
  el: "Greek",
  he: "Hebrew",
  hi: "Hindi",
  id: "Indonesian",
};

const DEFAULT_TTS_VOICE = "Joanna";
const DEFAULT_TTS_LANGUAGE = "en-US";
const DEFAULT_TTS_RATE = 1.0;

const PREDEFINED_CHARACTER_TAGS = [
  "Female",
  "Male",
  "Human",
  "Roleplay",
  "Hero",
  "Villain",
  "Politics",
  "Princess",
  "Prince",
  "Mermaid",
  "NSFW",
  "NSFL",
  "Disney",
  "Cartoon",
  "Movies & TV",
  "Games",
  "Multiple Characters",
  "Slice of Life",
  "Experimental",
  "Psychological",
  "College",
  "High School",
  "Fantasy",
  "Sci-Fi",
  "Romance",
  "Horror",
  "Adventure",
  "Comedy",
  "Drama",
  "Historical",
  "Mystery",
  "Action",
  "Cyberpunk",
  "Medieval",
  "Modern",
  "Anime",
  "Supernatural",
  "Crime",
  "Detective",
  "Military",
  "Space",
];

const I18N = {
  en: {
    threads: "Threads",
    createCharacter: "+ Character",
    importCharacter: "Import Character",
    settings: "Settings",
    home: "HOME",
    database: "Database",
    personas: "Personas",
    loreBooks: "Lorebooks",
    shortcuts: "Shortcuts",
    tags: "Tags",
    guide: "Guide",
    databaseManagement: "Database Management",
    exportDatabase: "Export Database",
    importDatabase: "Import Database",
    databaseHint:
      "Import will overwrite the current local data (characters, threads, settings, UI state, and more).",
    back: "Back",
    previousPrompts: "Previous prompts",
    chatOpacityTitle: "Transparency",
    chatOpacityToggle: "Adjust transparency",
    chatOpacityClose: "Done",
    send: "Send",
    cancel: "Cancel",
    hideShortcuts: "Hide Shortcuts",
    showShortcuts: "Show Shortcuts",
    autoReply: "Auto-reply",
    enterToSend: "ENTER to send",
    settingsTitle: "Settings",
    exportSettingsTitle: "Export all settings",
    importSettingsTitle: "Import all settings",
    tabAppearance: "Appearance",
    tabApi: "API",
    tabTts: "TTS",
    tabThreads: "Threads",
    tabShortcuts: "Shortcuts",
    tabPrompting: "Prompting",
    togglePane: "Toggle pane",
    clear: "Clear",
    filterByTag: "Filter by tag",
    characterOrdering: "Character ordering",
    lastModifiedNewest: "Last Modified: Newest",
    lastModifiedOldest: "Last Modified: Oldest",
    threadsMost: "Threads: Most",
    threadsLeast: "Threads: Least",
    tagFiltersActive: "Tag filters active.",
    editCurrentCharacter: "Edit current character",
    scrollToBottom: "Scroll to bottom",
    promptHistory: "Prompt history",
    promptPlaceholder:
      "What do you say or do? Enter to send, Shift+Enter for newline",
    selectedPersonaAvatar: "Persona avatar",
    selectPersona: "Select persona",
    confirm: "Confirm",
    ok: "OK",
    message: "Message",
    input: "Input",
    value: "Value",
    save: "Save",
    deleteMessageTitle: "Delete message",
    deleteMessageConfirm: "Delete this message?{preview}",
    unknownError: "unknown error",
    importFailed: "Import failed: {error}",
    databaseImportConfirm:
      "This will overwrite current local data completely. Continue?",
    databaseExportFailed: "Database export failed: {error}",
    databaseImportFailed: "Database import failed: {error}",
    shortcutsSaved: "Shortcuts saved.",
    tagsUpdated: "Tags updated.",
    characterUpdated: "Character updated.",
    characterCreated: "Character created.",
    characterDuplicated: "Character duplicated.",
    characterDeleted: "Character deleted.",
    characterNotFound: "Character not found.",
    characterExported: "Character exported.",
    characterImported: "Character imported.",
    personaUpdated: "Persona updated.",
    personaCreated: "Persona created.",
    personaDeleted: "Persona deleted.",
    defaultPersonaUpdated: "Default persona updated.",
    loreImportSoon: "Lorebook import will be added soon.",
    loreExportSoon: "Lorebook export will be added soon.",
    loreUpdated: "Lorebook updated.",
    loreCreated: "Lorebook created.",
    loreDuplicated: "Lorebook duplicated.",
    loreDeleted: "Lorebook deleted.",
    databaseExported: "Database exported.",
    settingsExported: "Settings exported.",
    settingsImported: "Settings imported successfully.",
    importSettingsConfirmTitle: "Import Settings",
    importSettingsConfirmMessage:
      "This will replace all your current settings. Are you sure?",
    importSettingsFailed: "Failed to import settings.",
    databaseImportedReloading: "Database imported. Reloading...",
    threadCreated: "Thread created.",
    threadDuplicated: "Thread duplicated.",
    threadForked: "Thread forked.",
    threadTitleForked: "Fork of {title}",
    msgForkTitle: "Fork chat from here",
    threadFavorited: "Thread favorited.",
    threadUnfavorited: "Thread unfavorited.",
    threadDeleted: "Thread deleted.",
    threadRenamed: "Thread renamed.",
    generationCancelled: "Generation cancelled.",
    generationFailed: "Generation failed.",
    regenerationCancelled: "Regeneration cancelled.",
    messageCopied: "Message copied.",
    missingFieldTitle: "Missing Field",
    invalidFileTitle: "Invalid File",
    pleaseChooseImageFile: "Please choose an image file.",
    dropFailedTitle: "Drop Failed",
    dropReadFailed: "Unable to read dropped file as text.",
    loadedFileIntoField: "Loaded {name} into field.",
    messageUpdated: "Message updated.",
    openThreadFirst: "Open a thread first.",
    ttsAssistantOnly: "TTS is only available for assistant messages.",
    messageEmpty: "Message is empty.",
    ttsFailed: "TTS failed: {error}",
    ttsTestFailed: "TTS test failed: {error}",
    personaSwitched: "Persona switched to {name}.",
    personaDescriptionTitle: "Persona Description",
    personaDescriptionLimit:
      "Persona description must be 100 characters or less.",
    noPersonasYet: "No personas yet.",
    dragToReorder: "Drag to reorder",
    defaultSuffix: "Default",
    globalDefaultSuffix: "Global Default",
    threadWord: "Thread",
    threadTitleDefault: "Thread {id}",
    threadTitleAtDate: "Thread {date}",
    createdAtLabel: "Created: {value}",
    updatedAtLabel: "Updated: {value}",
    characterIdThreadCount: "char #{id} - {count} threads",
    less: "less",
    more: "more...",
    noTagsMatched: "No characters match the active tag filters.",
    noCharactersStart: "No characters yet. Create one to begin.",
    selectAllThreads: "Select all threads",
    selectThread: "Select thread",
    deleteSelectedThreads: "Delete selected threads",
    deleteThreadsTitle: "Delete Threads",
    deleteSelectedThreadsConfirm: "Delete {count} selected thread{suffix}?",
    deletedThreadsToast: "{count} thread{suffix} deleted.",
    editThreadCharacter: "Edit thread character",
    deleteThreadAria: "Delete thread",
    duplicateThreadAria: "Duplicate thread",
    favoriteThread: "Favorite thread",
    unfavoriteThread: "Unfavorite thread",
    renameThreadAria: "Rename thread",
    deleteCharacterAria: "Delete character",
    duplicateCharacterAria: "Duplicate character",
    editCharacterAria: "Edit character",
    exportCharacterAria: "Export character",
    deletePersonaTitle: "Delete Persona",
    deletePersonaConfirm: "Delete this persona?",
    editPersonaAria: "Edit persona",
    deleteLoreBookTitle: "Delete Lorebook",
    deleteThreadTitle: "Delete Thread",
    deleteThreadConfirm: "Delete this thread?",
    editLoreBookAria: "Edit Lorebook",
    deleteLoreBookAria: "Delete Lorebook",
    invalidLoreBookTitle: "Invalid Lorebook",
    invalidLoreEntryTitle: "Invalid Lore Entry",
    loreAtLeastOneEntry: "At least one lore entry is required.",
    invalidInitialMessagesTitle: "Invalid Initial Messages",
    invalidInitialMessagesMessage: "Could not parse initial messages.",
    characterNameRequired: "Character name is required.",
    characterNameRequiredAllLanguages:
      "Character name is required in all language tabs. Missing: {langs}.",
    personaNameRequired: "Persona name is required.",
    threadTitleRequired: "Thread title is required.",
    renameThreadTitle: "Rename Thread",
    threadTitleLabel: "Thread Title",
    updatePersona: "Update Persona",
    regenerateFailedTitle: "Regenerate Failed",
    copyFailedTitle: "Copy Failed",
    copyFailedMessage: "Unable to copy message.",
    autoTtsEnabled: "Auto TTS enabled.",
    autoTtsDisabled: "Auto TTS disabled.",
    autoTtsTitleOn: "Auto TTS: On",
    autoTtsTitleOff: "Auto TTS: Off",
    enableAutoTtsAria: "Enable auto TTS",
    disableAutoTtsAria: "Disable auto TTS",
    threadBudgetUnavailable: "Thread budget unavailable.",
    settingsTtsTestTitle: "Play TTS Test",
    msgDeleteTitle: "Delete message",
    msgRegenerateTitle: "Regenerate message",
    msgEditTitle: "Edit message",
    msgCopyTitle: "Copy message",
    msgMetadataTitle: "Message metadata",
    msgSpeakTitle: "Speak message",
    msgSpeakCancelTitle: "Cancel speech",
    msgSpeakLoadingTitle: "Loading speech... Click again to cancel.",
    msgVoiceUnavailableTitle:
      "Voice support is not configured in this browser.",
    msgVoiceUnavailableAria: "Voice support unavailable",
    msgMetadataUnavailableEdited:
      "Metadata is not available in user edited messages.",
    msgMetadataUnavailableEditedAria:
      "Metadata unavailable for user edited message",
    msgMetadataUnavailableInitial:
      "Metadata is not available for initial messages.",
    msgMetadataUnavailableInitialAria:
      "Metadata unavailable for initial message",
    msgMetadataUnavailableGenerating: "Metadata unavailable while generating.",
    msgMetadataUnavailableGeneratingAria:
      "Metadata unavailable while generating",
    threadBudgetTooltip:
      "Estimated effective output budget for this thread.\nUser max: {userMax}\nModel context: {contextText}\nEstimated prompt tokens: {promptTokens}\nSafety margin: 256\nEffective max_tokens: {effectiveMax}",
    generationQueuedToast: "Generation queued (position {position}).",
    generationQueuedNotice: "Generation queued. Waiting for active generation.",
    generationQueuedNoticeWithPos:
      "Generation queued. Waiting for active generation (queue position {position}).",
    guideComingSoon: "Guide will be added soon.",
    queuedLabel: "Queued {position}/{size}",
    generatingLabel: "Generating...",
    regeneratingLabel: "Regenerating...",
    truncatedMessageLine1:
      "This message has been truncated by the currently active model.",
    truncatedMessageLine2:
      "You can delete or regenerate this message. You can also trigger another model response, or send a new message.",
    generationErrorLine1: "Generation failed for this message.",
    generationErrorLine3:
      "You can regenerate this message, switch model, or continue the chat.",
    threadQueueBadgeTitle: "Queued for generation (position {position})",

    chatMessageAlignment: "Message Alignment",
    messageAlignmentLeft: "Left (Default)",
    messageAlignmentCenter: "Center",
    resetAppData: "Reset App Data",
    openRouterApiKey: "OpenRouter API Key",
    modelLabel: "Model",
    pricingLabel: "Pricing",
    modalityLabel: "Modality",
    orderLabel: "Order",
    all: "All",
    free: "Free",
    paid: "Paid",
    textToText: "Text -> Text",
    nameAsc: "Name A-Z",
    nameDesc: "Name Z-A",
    createdNewest: "Created Newest",
    createdOldest: "Created Oldest",
    reload: "Reload",
    modelNotRecommendedRoleplay:
      "This model is NOT recommended for roleplaying.",
    maxTokensLabel: "Max Tokens",
    temperatureLabel: "Temperature",
    toastDelayLabel: "Toast Delay",
    cooldownToastActive: "Cooldown active: {seconds}s",
    marqueeBehaviorLabel: "Marquee Behavior",
    marqueeBehaviorDisabled: "Disabled",
    marqueeBehaviorOnHover: "On Hover",
    marqueeBehaviorAlways: "Always",
    ttsTestTextLabel: "TTS Test Text",
    playTtsTest: "Play TTS Test",
    renderMarkdown: "Render Markdown in messages",
    allowRawHtml: "Allow raw HTML in messages",
    stream: "Stream",
    streamMessages: "Stream Messages",
    autoTitleSettings: "Auto-Title",
    summarySettings: "Summary",
    oocSettings: "OOC",
    enableOocSettings: "Use OOC Settings",
    oocProvider: "OOC Provider",
    oocModel: "OOC Model",
    oocTemperature: "OOC Temperature",
    oocStopStrings: "OOC Stop Strings",
    oocStream: "OOC Stream",
    autoPairSymbols: "Auto-pair editor symbols",
    markdownCustomCss: "Markdown Custom CSS",
    postprocessRules: "Post-processing Rules (JSON)",
    cancelGenerationShortcut: "Cancel Generation Shortcut",
    goHomeShortcut: "Go Home Shortcut",
    newCharacterShortcut: "New Character Shortcut",
    defaultCharacterPrompt: "Default Character Prompt",
    memorySummarizerPrompt: "Memory Summarizer System Prompt",
    memoryRelevanceFilterToggle: "Use memory relevance filter",
    personaInjectionTemplate: "Persona Injection Template",
    writingInstructionsInjectionTiming: "Writing Instructions Injection Timing",
    always: "Always",
    everyOther: "Every Other",
    everySecond: "Every Second",
    everyThird: "Every Third",
    everyFourth: "Every Fourth",
    nameLabel: "Name",
    avatarUrl: "Avatar URL",
    avatars: "Avatars",
    avatarFile: "Avatar File",
    personaDescription: "Description (max 100 chars)",
    personaInternalDescription: "Internal Description (optional)",
    setDefaultPersona: "Set as default persona",
    savePersona: "Save Persona",
    loreBookManagement: "Lorebook Management",
    createLoreBook: "+ Create Lorebook",
    importLoreBook: "^ Import Lorebook",
    backToList: "< Back to List",
    avatarUrlOptional: "Avatar URL (optional)",
    descriptionOptional: "Description (optional)",
    scanDepth: "Scan Depth",
    tokenBudget: "Token Budget",
    recursiveScanning: "Recursive Scanning",
    addEntry: "+ Add Entry",
    saveLoreBook: "Save Lorebook",
    shortcutEntries: "Shortcut Entries",
    saveShortcuts: "Save Shortcuts",
    tagManager: "Tag Manager",
    tagInputPlaceholder: "New tag",
    removeTagTitle: "Remove Tag",
    removeTagConfirmSimple: "Remove this tag?",
    removeTagAffectsChars:
      "Removing this tag will update these characters:\n\n{list}{extra}\n\nContinue?",
    createCharacterTitle: "Create Character",
    editCharacterTitle: "Edit Character",
    characterPrompt: "Character Prompt",
    oneTimeExtraPrompt: "One-time Only Extra Prompt",
    writingInstructions: "Writing Instructions",
    writingInstructionsNone: "None",
    apply: "Apply",
    closeWithoutSaving: "Close Without Saving",
    saveAndClose: "Save and Close",
    initialMessages: "Initial Messages",
    tagsCommaSeparated: "Tags (comma-separated)",
    personaInjectionPlacement: "Persona Injection Placement",
    atEndCharacterPrompt: "At End of Character Prompt",
    botConfiguration: "Config",
    bgTab: "BG",
    tagsTab: "Tags",
    addLanguage: "Add Language",
    add: "Add",
    enableTts: "Enable TTS",
    removeLanguageTitle: "Remove Language",
    removeLanguageConfirm: "Remove language definition {lang}?",
    removeLanguageConfirmWithThreads:
      "Remove language definition {lang}? This will delete {count} thread(s) using this language.",
    languageRequired: "At least one language definition is required.",
    enableMemory: "Enable Memory",
    enablePostprocess: "Enable Post-processing Rules",
    autoTriggerAiFirst: "Auto-trigger AI first message",
    avatarScaleInChat: "Avatar Scale (In Chat)",
    ttsProvider: "TTS Provider",
    ttsLanguage: "TTS Language",
    ttsVoice: "TTS Voice",
    ttsRate: "TTS Rate",
    ttsPitch: "TTS Pitch",
    testCharacterVoice: "Test Character Voice",
    stopCharacterVoiceTest: "Stop character voice test",
    loreBooksForCharacter: "Lorebooks for this character",
    createdLabel: "Created",
    updatedLabel: "Updated",
    threadsLower: "threads",
    charPrefix: "char",
    noCharactersMatchTags: "No characters match the active tag filters.",
    noCharactersYet: "No characters yet. Create one to begin.",
    noThreadsYet: "No threads yet.",
    languageLabel: "Interface Language",
    languageAuto: "Auto (browser)",
    languageEnglish: "English",
    languageFrench: "Francais",
    languageItalian: "Italiano",
    languageGerman: "Deutsch",
    languageSpanish: "Espanol",
    languagePortugueseBr: "Portugues (Brasil)",
  },
  fr: {
    threads: "Fils",
    createCharacter: "+ Personnage",
    importCharacter: "Importer personnage",
    settings: "ParamÃ¨tres",
    personas: "Personas",
    loreBooks: "Livres de lore",
    shortcuts: "Raccourcis",
    back: "Retour",
    previousPrompts: "Prompts prÃ©cÃ©dents",
    send: "Envoyer",
    cancel: "Annuler",
    hideShortcuts: "Masquer raccourcis",
    showShortcuts: "Afficher raccourcis",
    autoReply: "RÃ©ponse auto",
    enterToSend: "ENTRÃ‰E pour envoyer",
    settingsTitle: "ParamÃ¨tres",
    exportSettingsTitle: "Exporter tous les paramÃ¨tres",
    importSettingsTitle: "Importer tous les paramÃ¨tres",
    languageLabel: "Langue de l'interface",
    languageAuto: "Auto (navigateur)",
    languageEnglish: "English",
    languageFrench: "FranÃ§ais",
    languageItalian: "Italiano",
    languageGerman: "Deutsch",
    languageSpanish: "EspaÃ±ol",
    languagePortugueseBr: "PortuguÃªs (Brasil)",
  },
  it: {
    threads: "Thread",
    createCharacter: "+ Personaggio",
    importCharacter: "Importa personaggio",
    settings: "Impostazioni",
    personas: "Persona",
    loreBooks: "Libri lore",
    shortcuts: "Scorciatoie",
    back: "Indietro",
    previousPrompts: "Prompt precedenti",
    send: "Invia",
    cancel: "Annulla",
    hideShortcuts: "Nascondi scorciatoie",
    showShortcuts: "Mostra scorciatoie",
    autoReply: "Risposta automatica",
    enterToSend: "INVIO per inviare",
    settingsTitle: "Impostazioni",
    exportSettingsTitle: "Esporta tutte le impostazioni",
    importSettingsTitle: "Importa tutte le impostazioni",
    languageLabel: "Lingua interfaccia",
    languageAuto: "Auto (browser)",
    languageEnglish: "English",
    languageFrench: "FranÃ§ais",
    languageItalian: "Italiano",
    languageGerman: "Deutsch",
    languageSpanish: "EspaÃ±ol",
    languagePortugueseBr: "PortuguÃªs (Brasil)",
  },
  de: {
    threads: "Threads",
    createCharacter: "+ Charakter",
    importCharacter: "Charakter importieren",
    settings: "Einstellungen",
    personas: "Personas",
    loreBooks: "Lore-BÃ¼cher",
    shortcuts: "Shortcuts",
    back: "ZurÃ¼ck",
    previousPrompts: "Vorherige Prompts",
    send: "Senden",
    cancel: "Abbrechen",
    hideShortcuts: "Shortcuts ausblenden",
    showShortcuts: "Shortcuts anzeigen",
    autoReply: "Auto-Antwort",
    enterToSend: "ENTER zum Senden",
    settingsTitle: "Einstellungen",
    exportSettingsTitle: "Alle Einstellungen exportieren",
    importSettingsTitle: "Alle Einstellungen importieren",
    languageLabel: "Sprache",
    languageAuto: "Auto (Browser)",
    languageEnglish: "English",
    languageFrench: "FranÃ§ais",
    languageItalian: "Italiano",
    languageGerman: "Deutsch",
    languageSpanish: "EspaÃ±ol",
    languagePortugueseBr: "PortuguÃªs (Brasil)",
  },
  es: {
    threads: "Hilos",
    createCharacter: "+ Personaje",
    importCharacter: "Importar personaje",
    settings: "ConfiguraciÃ³n",
    personas: "Personas",
    loreBooks: "Libros de lore",
    shortcuts: "Atajos",
    back: "Volver",
    previousPrompts: "Prompts anteriores",
    send: "Enviar",
    cancel: "Cancelar",
    hideShortcuts: "Ocultar atajos",
    showShortcuts: "Mostrar atajos",
    autoReply: "Respuesta automÃ¡tica",
    enterToSend: "ENTER para enviar",
    settingsTitle: "ConfiguraciÃ³n",
    exportSettingsTitle: "Exportar toda la configuraciÃ³n",
    importSettingsTitle: "Importar toda la configuraciÃ³n",
    languageLabel: "Idioma de interfaz",
    languageAuto: "Auto (navegador)",
    languageEnglish: "English",
    languageFrench: "FranÃ§ais",
    languageItalian: "Italiano",
    languageGerman: "Deutsch",
    languageSpanish: "EspaÃ±ol",
    languagePortugueseBr: "PortuguÃªs (Brasil)",
  },
  "pt-BR": {
    threads: "Conversas",
    createCharacter: "+ Personagem",
    importCharacter: "Importar personagem",
    settings: "ConfiguraÃ§Ãµes",
    personas: "Personas",
    loreBooks: "Livros de lore",
    shortcuts: "Atalhos",
    back: "Voltar",
    previousPrompts: "Prompts anteriores",
    send: "Enviar",
    cancel: "Cancelar",
    hideShortcuts: "Ocultar atalhos",
    showShortcuts: "Mostrar atalhos",
    autoReply: "Resposta automÃ¡tica",
    enterToSend: "ENTER para enviar",
    settingsTitle: "ConfiguraÃ§Ãµes",
    exportSettingsTitle: "Exportar todas as configuraÃ§Ãµes",
    importSettingsTitle: "Importar todas as configuraÃ§Ãµes",
    languageLabel: "Idioma da interface",
    languageAuto: "AutomÃ¡tico (navegador)",
    languageEnglish: "English",
    languageFrench: "FranÃ§ais",
    languageItalian: "Italiano",
    languageGerman: "Deutsch",
    languageSpanish: "EspaÃ±ol",
    languagePortugueseBr: "PortuguÃªs (Brasil)",
  },
};
