// constants.js

const MODEL_OPTIONS = [
  { value: "openrouter/auto", label: "Auto" },
  { value: "openrouter/free", label: "OpenRouter Free Router" },
  {
    value: "meta-llama/llama-4-maverick:free",
    label: "Llama 4 Maverick (free)",
  },
  { value: "meta-llama/llama-4-scout:free", label: "Llama 4 Scout (free)" },
  {
    value: "meta-llama/llama-3.1-8b-instruct:free",
    label: "Llama 3.1 8B (free)",
  },
  {
    value: "mistralai/mistral-small-3.1-24b-instruct:free",
    label: "Mistral Small 24B (free)",
  },
  { value: "google/gemma-3-12b-it:free", label: "Gemma 3 12B (free)" },
  { value: "deepseek/deepseek-chat-v3-0324:free", label: "DeepSeek V3 (free)" },
  { value: "deepseek/deepseek-r1", label: "DeepSeek R1" },
  { value: "deepseek/deepseek-r1:free", label: "DeepSeek R1 (free)" },
  {
    value: "nousresearch/hermes-3-llama-3.1-405b:free",
    label: "Hermes 3 Llama 3.1 405B (free)",
  },
  { value: "stepfun/step-3.5-flash:free", label: "StepFun Flash (free)" },
  {
    value: "cognitivecomputations/dolphin-mistral-24b-venice-edition:free",
    label: "Dolphin Mistral 24B Venice Edition (free)",
  },
  {
    value: "arcee-ai/trinity-large-preview:free",
    label: "Trinity Large Preview (free)",
  },
];

const ICONS = {
  duplicate:
    '<svg viewBox="0 0 24 24" aria-hidden="true"><rect x="9" y="9" width="11" height="11" rx="2"></rect><rect x="4" y="4" width="11" height="11" rx="2"></rect></svg>',
  fork: '<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="6" cy="6" r="2.5"></circle><circle cx="18" cy="6" r="2.5"></circle><circle cx="12" cy="18" r="2.5"></circle><path d="M6 8.5v3"></path><path d="M18 8.5v3"></path><path d="M6 12.5h12"></path><path d="M12 12.5v5.5"></path></svg>',
  edit: '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 20l4.2-1 10-10a2 2 0 0 0-2.8-2.8l-10 10L4 20z"></path><path d="M13.5 6.5l4 4"></path></svg>',
  delete:
    '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 7h16"></path><path d="M9 7V5h6v2"></path><path d="M7 7l1 13h8l1-13"></path><path d="M10 11v6"></path><path d="M14 11v6"></path></svg>',
  regenerate:
    '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M20 12a8 8 0 1 1-2.3-5.7"></path><path d="M20 4v6h-6"></path></svg>',
  copy: '<svg viewBox="0 0 24 24" aria-hidden="true"><rect x="9" y="9" width="11" height="11" rx="2"></rect><rect x="4" y="4" width="11" height="11" rx="2"></rect></svg>',
  plus: '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 5v14"></path><path d="M5 12h14"></path></svg>',
  speaker:
    '<svg viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M4 14v-4h4l5-4v12l-5-4H4z"></path><path d="M16 9a4 4 0 0 1 0 6"></path><path d="M18.5 7a7 7 0 0 1 0 10"></path></svg>',
  brain:
    '<svg viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M18 11h-1a3 3 0 0 0-3-3h-1v-1a2 2 0 0 0-2-2h-1a2 2 0 0 0-2 2v1H9a3 3 0 0 0-3 3H5a3 3 0 0 0 0 6h1v2a3 3 0 0 0 6 0v-2h2a3 3 0 0 0 6 0v-2h1a3 3 0 0 0 0-6h-1z"></path><path d="M12 6v4"></path><path d="M8 11h8"></path><path d="M12 14v4"></path></svg>',
  stop: '<svg viewBox="0 0 24 24" aria-hidden="true"><rect x="6" y="6" width="12" height="12" rx="2"></rect></svg>',
  mic: '<svg viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M12 14c1.66 0 3-1.34 3-3V5c0-1.66-1.34-3-3-3S9 3.34 9 5v6c0 1.66 1.34 3 3 3z"></path><path d="M17 11c0 2.76-2.24 5-5 5s-5-2.24-5-5H5c0 3.53 2.61 6.43 6 6.92V21h2v-3.08c3.39-.49 6-3.39 6-6.92h-2z"></path></svg>',
  micFilled: '<svg viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M12 14c1.66 0 3-1.34 3-3V5c0-1.66-1.34-3-3-3S9 3.34 9 5v6c0 1.66 1.34 3 3 3z"></path><path d="M17 11c0 2.76-2.24 5-5 5s-5-2.24-5-5H5c0 3.53 2.61 6.43 6 6.92V21h2v-3.08c3.39-.49 6-3.39 6-6.92h-2z"></path></svg>',
  info: '<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="9"></circle><path d="M12 10v6"></path><circle cx="12" cy="7.5" r="1"></circle></svg>',
  context:
    '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M9 5a3 3 0 0 1 5.7-1.2A3.2 3.2 0 0 1 18 7v.2a3 3 0 0 1 1 5.7A3.2 3.2 0 0 1 16 18h-1a3 3 0 0 1-6 0H8a3.2 3.2 0 0 1-3-5.1A3 3 0 0 1 6 7v-.2A3.2 3.2 0 0 1 9 5z"></path><path d="M10 9.5v5"></path><path d="M14 9.5v5"></path><path d="M10 12h4"></path></svg>',
  model:
    '<svg viewBox="0 0 24 24" aria-hidden="true"><rect x="4" y="4" width="16" height="16" rx="2"></rect><path d="M9 9h6v6H9z"></path><path d="M9 2v2M15 2v2M9 20v2M15 20v2M2 9h2M2 15h2M20 9h2M20 15h2"></path></svg>',
  star: '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 3l2.7 5.5 6.1.9-4.4 4.3 1 6.1-5.4-2.8-5.4 2.8 1-6.1-4.4-4.3 6.1-.9z"></path></svg>',
  starFilled:
    '<svg viewBox="0 0 24 24" aria-hidden="true"><path fill="currentColor" stroke="none" d="M12 3l2.7 5.5 6.1.9-4.4 4.3 1 6.1-5.4-2.8-5.4 2.8 1-6.1-4.4-4.3 6.1-.9z"></path></svg>',
  badge:
    '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 3l7 3v6c0 5-3.1 8.6-7 9-3.9-.4-7-4-7-9V6z"></path><path d="M9.2 12.2l1.9 1.9 3.7-3.7"></path></svg>',
  export:
    '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 3v12"></path><path d="M8 7l4-4 4 4"></path><path d="M4 14v5h16v-5"></path></svg>',
  pin: '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 2C8.1 2 5 5.1 5 9c0 5.3 7 13 7 13s7-7.8 7-13c0-3.9-3.1-7-7-7z"></path><circle cx="12" cy="9" r="2"></circle></svg>',
  pinFilled:
    '<svg viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M12 2C8.1 2 5 5.1 5 9c0 5.3 7 13 7 13s7-7.8 7-13c0-3.9-3.1-7-7-7z"></path><circle cx="12" cy="9" r="2"></circle></svg>',
};

const PROMPT_COMMAND_HISTORY_KEY = "rp-prompt-command-history";
const PROMPT_COMMAND_HISTORY_MAX = 200;
const PROMPT_HISTORY_KEY = "rp-prompt-history";
const PROMPT_HISTORY_MAX = 200;

const DEFAULT_PERSONA_COLOR = "#7c5cff";
const DEFAULT_CHAT_OPACITY = 1;
const DEFAULT_THREAD_TINT_INPUT_COLOR = "#7c5cff";

const CHARACTER_PAGE_SIZES = [0, 5, 10, 20, 50];
const CHARACTER_PAGE_BUTTON_WINDOW = 7;

const USER_INPUT_AUTO_EXPAND_MAX_HEIGHT = 280;

const DEFAULT_KOKORO_VOICE = "af_heart";
const KOKORO_MODEL_ID = "onnx-community/Kokoro-82M-v1.0-ONNX";

const KOKORO_MODULE_PATHS = [
  "https://cdn.jsdelivr.net/npm/kokoro-js@1.2.1/dist/kokoro.web.js",
];

const KOKORO_DEVICE_OPTIONS = ["wasm", "webgpu"];
const KOKORO_DTYPE_OPTIONS = [
  "fp16",
  "q8",
  "q4",
  "q4f16",
  "q8f16",
  "auto",
  "uint8",
  "uint8f16",
];
const KOKORO_DTYPE_LABELS = {
  fp16: "FP16",
  q8: "Q8",
  q4: "Q4",
  q4f16: "Q4f16",
  q8f16: "Q8f16",
  auto: "AUTO",
  uint8: "UINT8",
  uint8f16: "UINT8F16",
};
const KOKORO_VOICE_OPTIONS = [
  "af_alloy",
  "af_aoede",
  "af_bella",
  "af_heart",
  "af_jessica",
  "af_kore",
  "af_nicole",
  "af_nova",
  "af_river",
  "af_sarah",
  "af_sky",
  "am_adam",
  "am_echo",
  "am_eric",
  "am_fenrir",
  "am_liam",
  "am_michael",
  "am_onyx",
  "am_puck",
  "am_santa",
  "bf_alice",
  "bf_emma",
  "bf_isabella",
  "bf_lily",
  "bm_daniel",
  "bm_fable",
  "bm_george",
  "bm_lewis",
  "ef_dora",
  "em_alex",
  "em_santa",
  "ff_siwis",
  "hf_alpha",
  "hf_beta",
  "hm_omega",
  "hm_psi",
  "if_sara",
  "im_nicola",
  "jf_alpha",
  "jf_gongitsune",
  "jf_nezumi",
  "jf_tebukuro",
  "jm_kumo",
  "pf_dora",
  "pm_alex",
  "pm_santa",
  "zf_xiaobei",
  "zf_xiaoni",
  "zf_xiaoxiao",
  "zf_xiaoyi",
  "zm_yunjian",
  "zm_yunxi",
  "zm_yunxia",
  "zm_yunyang",
];

const KOKORO_LANGUAGE_VOICE_PREFIXES = {
  en: ["af", "am", "bf", "bm"],
  fr: ["ff"],
  it: ["if", "im"],
  ja: ["jf", "jm"],
  zh: ["zf", "zm"],
  hi: ["hf", "hm"],
  "pt-BR": ["pf", "pm"],
  pt: ["pf", "pm"],
};

const UI_LANG_OPTIONS = ["en", "fr", "it", "de", "es", "pt-BR"];
const LOCALES_BASE_PATH = "locales";
const BOT_LANGUAGE_OPTIONS = [
  "en",
  "fr",
  "it",
  "de",
  "es",
  "pt-BR",
  "pt-PT",
  "ja",
  "ko",
  "zh-CN",
  "zh-TW",
  "ru",
  "ar",
  "nl",
  "tr",
  "pl",
  "sv",
  "da",
  "fi",
  "no",
  "cs",
  "ro",
  "hu",
  "el",
  "he",
  "hi",
  "id",
  "th",
  "vi",
];

const BOT_LANGUAGE_FLAGS = {
  en: "ðŸ‡ºðŸ‡¸",
  fr: "ðŸ‡«ðŸ‡·",
  it: "ðŸ‡®ðŸ‡¹",
  de: "ðŸ‡©ðŸ‡ª",
  es: "ðŸ‡ªðŸ‡¸",
  "pt-BR": "ðŸ‡§ðŸ‡·",
  "pt-PT": "ðŸ‡µðŸ‡¹",
  ja: "ðŸ‡¯ðŸ‡µ",
  ko: "ðŸ‡°ðŸ‡·",
  "zh-CN": "ðŸ‡¨ðŸ‡³",
  "zh-TW": "ðŸ‡¹ðŸ‡¼",
  ru: "ðŸ‡·ðŸ‡º",
  ar: "ðŸ‡¸ðŸ‡¦",
  nl: "ðŸ‡³ðŸ‡±",
  tr: "ðŸ‡¹ðŸ‡·",
  pl: "ðŸ‡µðŸ‡±",
  sv: "ðŸ‡¸ðŸ‡ª",
  da: "ðŸ‡©ðŸ‡°",
  fi: "ðŸ‡«ðŸ‡®",
  no: "ðŸ‡³ðŸ‡´",
  cs: "ðŸ‡¨ðŸ‡¿",
  ro: "ðŸ‡·ðŸ‡´",
  hu: "ðŸ‡­ðŸ‡º",
  el: "ðŸ‡¬ðŸ‡·",
  he: "ðŸ‡®ðŸ‡±",
  hi: "ðŸ‡®ðŸ‡³",
  id: "ðŸ‡®ðŸ‡©",
  th: "ðŸ‡¹ðŸ‡­",
  vi: "ðŸ‡»ðŸ‡³",
};

const CHARACTER_SORT_BASES = ["created", "updated", "name", "threads"];
const CHARACTER_SORT_ICON_TEMPLATES = {
  created:
    '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><circle cx="16" cy="16" r="10" fill="%23f5f7ff" opacity="0.35"/><path d="M16 9v14M9 16h14" stroke="%231c2737" stroke-width="2" stroke-linecap="round"/></svg>',
  updated:
    '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><path d="M10 12a8 8 0 1 1 11.3 11.3L16 21" fill="none" stroke="%231c2737" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round"/><path d="M16 9v-4h6" fill="none" stroke="%231c2737" stroke-width="2.2" stroke-linecap="round" stroke-linejoin="round"/></svg>',
  name: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><text x="9" y="23" font-size="18" font-family="Segoe UI, system-ui" fill="%23f5f7ff">A</text><path d="M9 10l7 12l7-12" fill="none" stroke="%231c2737" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg>',
  threads:
    '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><rect x="6" y="8" width="20" height="4" rx="2" fill="%23f5f7ff" opacity="0.65"/><rect x="6" y="14" width="20" height="4" rx="2" fill="%23f5f7ff" opacity="0.45"/><rect x="6" y="20" width="20" height="4" rx="2" fill="%23f5f7ff" opacity="0.25"/><path d="M9 8v14" fill="none" stroke="%231c2737" stroke-width="2" stroke-linecap="round"/></svg>',
};
const CHARACTER_SORT_LABEL_KEYS = {
  created: "characterSortCreationDate",
  updated: "characterSortUpdateDate",
  name: "characterSortName",
  threads: "characterSortChats",
};

const BOT_LANGUAGE_FLAG_ICON_CODES = {
  en: "us",
  fr: "fr",
  it: "it",
  de: "de",
  es: "es",
  "pt-BR": "br",
  "pt-PT": "pt",
  ja: "jp",
  ko: "kr",
  "zh-CN": "cn",
  "zh-TW": "tw",
  ru: "ru",
  ar: "sa",
  nl: "nl",
  tr: "tr",
  pl: "pl",
  sv: "se",
  da: "dk",
  fi: "fi",
  no: "no",
  cs: "cz",
  ro: "ro",
  hu: "hu",
  el: "gr",
  he: "il",
  hi: "in",
  id: "id",
};

const BOT_LANGUAGE_NAMES = {
  en: "English",
  fr: "French",
  it: "Italian",
  de: "German",
  es: "Spanish",
  "pt-BR": "Portuguese (Brazil)",
  "pt-PT": "Portuguese (Portugal)",
  ja: "Japanese",
  ko: "Korean",
  "zh-CN": "Chinese (Simplified)",
  "zh-TW": "Chinese (Traditional)",
  ru: "Russian",
  ar: "Arabic",
  nl: "Dutch",
  tr: "Turkish",
  pl: "Polish",
  sv: "Swedish",
  da: "Danish",
  fi: "Finnish",
  no: "Norwegian",
  cs: "Czech",
  ro: "Romanian",
  hu: "Hungarian",
  el: "Greek",
  he: "Hebrew",
  hi: "Hindi",
  id: "Indonesian",
};

const DEFAULT_TTS_VOICE = "Joanna";
const DEFAULT_TTS_LANGUAGE = "en-US";
const DEFAULT_TTS_RATE = 1.0;

const PREDEFINED_CHARACTER_TAGS = [
  "Female",
  "Male",
  "Human",
  "Roleplay",
  "Hero",
  "Villain",
  "Politics",
  "Princess",
  "Prince",
  "Mermaid",
  "NSFW",
  "NSFL",
  "Disney",
  "Cartoon",
  "Movies & TV",
  "Games",
  "Multiple Characters",
  "Slice of Life",
  "Experimental",
  "Psychological",
  "College",
  "High School",
  "Fantasy",
  "Sci-Fi",
  "Romance",
  "Horror",
  "Adventure",
  "Comedy",
  "Drama",
  "Historical",
  "Mystery",
  "Action",
  "Cyberpunk",
  "Medieval",
  "Modern",
  "Anime",
  "Supernatural",
  "Crime",
  "Detective",
  "Military",
  "Space",
];

const I18N = {
  en: {
    threads: "Threads",
    createCharacter: "+ Character",
    importCharacter: "Import Character",
    settings: "Settings",
    home: "HOME",
    database: "Database",
    personas: "Personas",
    loreBooks: "Lorebooks",
    shortcuts: "Shortcuts",
    tags: "Tags",
    guide: "Guide",
    databaseManagement: "Database Management",
    exportDatabase: "Export Database",
    importDatabase: "Import Database",
    databaseHint:
      "Import will overwrite the current local data (characters, threads, settings, UI state, and more).",
    back: "Back",
    previousPrompts: "Previous prompts",
    chatOpacityTitle: "Transparency",
    chatOpacityToggle: "Adjust transparency",
    chatOpacityClose: "Done",
    send: "Send",
    cancel: "Cancel",
    hideShortcuts: "Hide Shortcuts",
    showShortcuts: "Show Shortcuts",
    autoReply: "Auto-reply",
    enterToSend: "ENTER to send",
    settingsTitle: "Settings",
    tabAppearance: "Appearance",
    tabApi: "API",
    tabTts: "TTS",
    tabThreads: "Threads",
    tabShortcuts: "Shortcuts",
    tabPrompting: "Prompting",
    togglePane: "Toggle pane",
    clear: "Clear",
    filterByTag: "Filter by tag",
    characterOrdering: "Character ordering",
    lastModifiedNewest: "Last Modified: Newest",
    lastModifiedOldest: "Last Modified: Oldest",
    threadsMost: "Threads: Most",
    threadsLeast: "Threads: Least",
    tagFiltersActive: "Tag filters active.",
    editCurrentCharacter: "Edit current character",
    scrollToBottom: "Scroll to bottom",
    promptHistory: "Prompt history",
    promptPlaceholder:
      "What do you say or do? Enter to send, Shift+Enter for newline",
    selectedPersonaAvatar: "Persona avatar",
    selectPersona: "Select persona",
    confirm: "Confirm",
    ok: "OK",
    message: "Message",
    input: "Input",
    value: "Value",
    save: "Save",
    deleteMessageTitle: "Delete message",
    deleteMessageConfirm: "Delete this message?{preview}",
    unknownError: "unknown error",
    importFailed: "Import failed: {error}",
    databaseImportConfirm:
      "This will overwrite current local data completely. Continue?",
    databaseExportFailed: "Database export failed: {error}",
    databaseImportFailed: "Database import failed: {error}",
    shortcutsSaved: "Shortcuts saved.",
    tagsUpdated: "Tags updated.",
    characterUpdated: "Character updated.",
    characterCreated: "Character created.",
    characterDuplicated: "Character duplicated.",
    characterDeleted: "Character deleted.",
    characterNotFound: "Character not found.",
    characterExported: "Character exported.",
    characterImported: "Character imported.",
    personaUpdated: "Persona updated.",
    personaCreated: "Persona created.",
    personaDeleted: "Persona deleted.",
    defaultPersonaUpdated: "Default persona updated.",
    loreImportSoon: "Lorebook import will be added soon.",
    loreExportSoon: "Lorebook export will be added soon.",
    loreUpdated: "Lorebook updated.",
    loreCreated: "Lorebook created.",
    loreDuplicated: "Lorebook duplicated.",
    loreDeleted: "Lorebook deleted.",
    databaseExported: "Database exported.",
    databaseImportedReloading: "Database imported. Reloading...",
    threadCreated: "Thread created.",
    threadDuplicated: "Thread duplicated.",
    threadForked: "Thread forked.",
    threadTitleForked: "Fork of {title}",
    msgForkTitle: "Fork chat from here",
    threadFavorited: "Thread favorited.",
    threadUnfavorited: "Thread unfavorited.",
    threadDeleted: "Thread deleted.",
    threadRenamed: "Thread renamed.",
    generationCancelled: "Generation cancelled.",
    generationFailed: "Generation failed.",
    regenerationCancelled: "Regeneration cancelled.",
    messageCopied: "Message copied.",
    missingFieldTitle: "Missing Field",
    invalidFileTitle: "Invalid File",
    pleaseChooseImageFile: "Please choose an image file.",
    dropFailedTitle: "Drop Failed",
    dropReadFailed: "Unable to read dropped file as text.",
    loadedFileIntoField: "Loaded {name} into field.",
    messageUpdated: "Message updated.",
    openThreadFirst: "Open a thread first.",
    ttsAssistantOnly: "TTS is only available for assistant messages.",
    messageEmpty: "Message is empty.",
    ttsFailed: "TTS failed: {error}",
    ttsTestFailed: "TTS test failed: {error}",
    personaSwitched: "Persona switched to {name}.",
    personaDescriptionTitle: "Persona Description",
    personaDescriptionLimit:
      "Persona description must be 100 characters or less.",
    noPersonasYet: "No personas yet.",
    dragToReorder: "Drag to reorder",
    defaultSuffix: "Default",
    globalDefaultSuffix: "Global Default",
    threadWord: "Thread",
    threadTitleDefault: "Thread {id}",
    threadTitleAtDate: "Thread {date}",
    createdAtLabel: "Created: {value}",
    updatedAtLabel: "Updated: {value}",
    characterIdThreadCount: "char #{id} - {count} threads",
    less: "less",
    more: "more...",
    noTagsMatched: "No characters match the active tag filters.",
    noCharactersStart: "No characters yet. Create one to begin.",
    selectAllThreads: "Select all threads",
    selectThread: "Select thread",
    deleteSelectedThreads: "Delete selected threads",
    deleteThreadsTitle: "Delete Threads",
    deleteSelectedThreadsConfirm: "Delete {count} selected thread{suffix}?",
    deletedThreadsToast: "{count} thread{suffix} deleted.",
    editThreadCharacter: "Edit thread character",
    deleteThreadAria: "Delete thread",
    duplicateThreadAria: "Duplicate thread",
    favoriteThread: "Favorite thread",
    unfavoriteThread: "Unfavorite thread",
    renameThreadAria: "Rename thread",
    deleteCharacterAria: "Delete character",
    duplicateCharacterAria: "Duplicate character",
    editCharacterAria: "Edit character",
    exportCharacterAria: "Export character",
    deletePersonaTitle: "Delete Persona",
    deletePersonaConfirm: "Delete this persona?",
    editPersonaAria: "Edit persona",
    deleteLoreBookTitle: "Delete Lorebook",
    deleteThreadTitle: "Delete Thread",
    deleteThreadConfirm: "Delete this thread?",
    editLoreBookAria: "Edit Lorebook",
    deleteLoreBookAria: "Delete Lorebook",
    invalidLoreBookTitle: "Invalid Lorebook",
    invalidLoreEntryTitle: "Invalid Lore Entry",
    loreAtLeastOneEntry: "At least one lore entry is required.",
    invalidInitialMessagesTitle: "Invalid Initial Messages",
    invalidInitialMessagesMessage: "Could not parse initial messages.",
    characterNameRequired: "Character name is required.",
    characterNameRequiredAllLanguages:
      "Character name is required in all language tabs. Missing: {langs}.",
    personaNameRequired: "Persona name is required.",
    threadTitleRequired: "Thread title is required.",
    renameThreadTitle: "Rename Thread",
    threadTitleLabel: "Thread Title",
    updatePersona: "Update Persona",
    regenerateFailedTitle: "Regenerate Failed",
    copyFailedTitle: "Copy Failed",
    copyFailedMessage: "Unable to copy message.",
    autoTtsEnabled: "Auto TTS enabled.",
    autoTtsDisabled: "Auto TTS disabled.",
    autoTtsTitleOn: "Auto TTS: On",
    autoTtsTitleOff: "Auto TTS: Off",
    enableAutoTtsAria: "Enable auto TTS",
    disableAutoTtsAria: "Disable auto TTS",
    threadBudgetUnavailable: "Thread budget unavailable.",
    settingsTtsTestTitle: "Play TTS Test",
    msgDeleteTitle: "Delete message",
    msgRegenerateTitle: "Regenerate message",
    msgEditTitle: "Edit message",
    msgCopyTitle: "Copy message",
    msgMetadataTitle: "Message metadata",
    msgSpeakTitle: "Speak message",
    msgSpeakCancelTitle: "Cancel speech",
    msgSpeakLoadingTitle: "Loading speech... Click again to cancel.",
    msgVoiceUnavailableTitle:
      "Voice support is not configured in this browser.",
    msgVoiceUnavailableAria: "Voice support unavailable",
    msgMetadataUnavailableEdited:
      "Metadata is not available in user edited messages.",
    msgMetadataUnavailableEditedAria:
      "Metadata unavailable for user edited message",
    msgMetadataUnavailableInitial:
      "Metadata is not available for initial messages.",
    msgMetadataUnavailableInitialAria:
      "Metadata unavailable for initial message",
    msgMetadataUnavailableGenerating: "Metadata unavailable while generating.",
    msgMetadataUnavailableGeneratingAria:
      "Metadata unavailable while generating",
    threadBudgetTooltip:
      "Estimated effective output budget for this thread.\nUser max: {userMax}\nModel context: {contextText}\nEstimated prompt tokens: {promptTokens}\nSafety margin: 256\nEffective max_tokens: {effectiveMax}",
    generationQueuedToast: "Generation queued (position {position}).",
    generationQueuedNotice: "Generation queued. Waiting for active generation.",
    generationQueuedNoticeWithPos:
      "Generation queued. Waiting for active generation (queue position {position}).",
    guideComingSoon: "Guide will be added soon.",
    queuedLabel: "Queued {position}/{size}",
    generatingLabel: "Generating...",
    regeneratingLabel: "Regenerating...",
    truncatedMessageLine1:
      "This message has been truncated by the currently active model.",
    truncatedMessageLine2:
      "You can delete or regenerate this message. You can also trigger another model response, or send a new message.",
    generationErrorLine1: "Generation failed for this message.",
    generationErrorLine3:
      "You can regenerate this message, switch model, or continue the chat.",
    threadQueueBadgeTitle: "Queued for generation (position {position})",

    chatMessageAlignment: "Message Alignment",
    messageAlignmentLeft: "Left (Default)",
    messageAlignmentCenter: "Center",
    resetAppData: "Reset App Data",
    resetAppDataSoon: "Reset app data will be added soon.",
    openRouterApiKey: "OpenRouter API Key",
    modelLabel: "Model",
    pricingLabel: "Pricing",
    modalityLabel: "Modality",
    orderLabel: "Order",
    all: "All",
    free: "Free",
    paid: "Paid",
    textToText: "Text -> Text",
    nameAsc: "Name A-Z",
    nameDesc: "Name Z-A",
    createdNewest: "Created Newest",
    createdOldest: "Created Oldest",
    reload: "Reload",
    modelNotRecommendedRoleplay:
      "This model is NOT recommended for roleplaying.",
    maxTokensLabel: "Max Tokens",
    temperatureLabel: "Temperature",
    toastDelayLabel: "Toast Delay",
    cooldownToastActive: "Cooldown active: {seconds}s",
    marqueeBehaviorLabel: "Marquee Behavior",
    marqueeBehaviorDisabled: "Disabled",
    marqueeBehaviorOnHover: "On Hover",
    marqueeBehaviorAlways: "Always",
    ttsTestTextLabel: "TTS Test Text",
    playTtsTest: "Play TTS Test",
    renderMarkdown: "Render Markdown in messages",
    allowRawHtml: "Allow raw HTML in messages",
    streamMessages: "Stream Messages",
    autoPairSymbols: "Auto-pair editor symbols",
    markdownCustomCss: "Markdown Custom CSS",
    postprocessRules: "Post-processing Rules (JSON)",
    cancelGenerationShortcut: "Cancel Generation Shortcut",
    goHomeShortcut: "Go Home Shortcut",
    newCharacterShortcut: "New Character Shortcut",
    defaultCharacterPrompt: "Default Character Prompt",
    memorySummarizerPrompt: "Memory Summarizer System Prompt",
    memoryRelevanceFilterToggle: "Use memory relevance filter",
    personaInjectionTemplate: "Persona Injection Template",
    writingInstructionsInjectionTiming: "Writing Instructions Injection Timing",
    always: "Always",
    everyOther: "Every Other",
    everySecond: "Every Second",
    everyThird: "Every Third",
    everyFourth: "Every Fourth",
    nameLabel: "Name",
    avatarUrl: "Avatar URL",
    avatars: "Avatars",
    avatarFile: "Avatar File",
    personaDescription: "Description (max 100 chars)",
    personaInternalDescription: "Internal Description (optional)",
    setDefaultPersona: "Set as default persona",
    savePersona: "Save Persona",
    loreBookManagement: "Lorebook Management",
    createLoreBook: "+ Create Lorebook",
    importLoreBook: "^ Import Lorebook",
    backToList: "< Back to List",
    avatarUrlOptional: "Avatar URL (optional)",
    descriptionOptional: "Description (optional)",
    scanDepth: "Scan Depth",
    tokenBudget: "Token Budget",
    recursiveScanning: "Recursive Scanning",
    addEntry: "+ Add Entry",
    saveLoreBook: "Save Lorebook",
    shortcutEntries: "Shortcut Entries",
    saveShortcuts: "Save Shortcuts",
    tagManager: "Tag Manager",
    tagInputPlaceholder: "New tag",
    removeTagTitle: "Remove Tag",
    removeTagConfirmSimple: "Remove this tag?",
    removeTagAffectsChars:
      "Removing this tag will update these characters:\n\n{list}{extra}\n\nContinue?",
    createCharacterTitle: "Create Character",
    editCharacterTitle: "Edit Character",
    characterPrompt: "Character Prompt",
    oneTimeExtraPrompt: "One-time only Extra System/Character Prompt",
    writingInstructions: "Writing Instructions",
    writingInstructionsNone: "None",
    apply: "Apply",
    closeWithoutSaving: "Close Without Saving",
    saveAndClose: "Save and Close",
    initialMessages: "Initial Messages",
    tagsCommaSeparated: "Tags (comma-separated)",
    personaInjectionPlacement: "Persona Injection Placement",
    atEndCharacterPrompt: "At End of Character Prompt",
    botConfiguration: "Config",
    bgTab: "BG",
    tagsTab: "Tags",
    addLanguage: "Add Language",
    add: "Add",
    enableTts: "Enable TTS",
    removeLanguageTitle: "Remove Language",
    removeLanguageConfirm: "Remove language definition {lang}?",
    removeLanguageConfirmWithThreads:
      "Remove language definition {lang}? This will delete {count} thread(s) using this language.",
    languageRequired: "At least one language definition is required.",
    enableMemory: "Enable Memory",
    enablePostprocess: "Enable Post-processing Rules",
    autoTriggerAiFirst: "Auto-trigger AI first message",
    avatarScaleInChat: "Avatar Scale (In Chat)",
    ttsProvider: "TTS Provider",
    ttsLanguage: "TTS Language",
    ttsVoice: "TTS Voice",
    ttsRate: "TTS Rate",
    ttsPitch: "TTS Pitch",
    testCharacterVoice: "Test Character Voice",
    stopCharacterVoiceTest: "Stop character voice test",
    loreBooksForCharacter: "Lorebooks for this character",
    createdLabel: "Created",
    updatedLabel: "Updated",
    threadsLower: "threads",
    charPrefix: "char",
    noCharactersMatchTags: "No characters match the active tag filters.",
    noCharactersYet: "No characters yet. Create one to begin.",
    noThreadsYet: "No threads yet.",
    languageLabel: "Interface Language",
    languageAuto: "Auto (browser)",
    languageEnglish: "English",
    languageFrench: "Francais",
    languageItalian: "Italiano",
    languageGerman: "Deutsch",
    languageSpanish: "Espanol",
    languagePortugueseBr: "Portugues (Brasil)",
  },
  fr: {
    threads: "Fils",
    createCharacter: "+ Personnage",
    importCharacter: "Importer personnage",
    settings: "ParamÃ¨tres",
    personas: "Personas",
    loreBooks: "Livres de lore",
    shortcuts: "Raccourcis",
    back: "Retour",
    previousPrompts: "Prompts prÃ©cÃ©dents",
    send: "Envoyer",
    cancel: "Annuler",
    hideShortcuts: "Masquer raccourcis",
    showShortcuts: "Afficher raccourcis",
    autoReply: "RÃ©ponse auto",
    enterToSend: "ENTRÃ‰E pour envoyer",
    settingsTitle: "ParamÃ¨tres",
    languageLabel: "Langue de l'interface",
    languageAuto: "Auto (navigateur)",
    languageEnglish: "English",
    languageFrench: "FranÃ§ais",
    languageItalian: "Italiano",
    languageGerman: "Deutsch",
    languageSpanish: "EspaÃ±ol",
    languagePortugueseBr: "PortuguÃªs (Brasil)",
  },
  it: {
    threads: "Thread",
    createCharacter: "+ Personaggio",
    importCharacter: "Importa personaggio",
    settings: "Impostazioni",
    personas: "Persona",
    loreBooks: "Libri lore",
    shortcuts: "Scorciatoie",
    back: "Indietro",
    previousPrompts: "Prompt precedenti",
    send: "Invia",
    cancel: "Annulla",
    hideShortcuts: "Nascondi scorciatoie",
    showShortcuts: "Mostra scorciatoie",
    autoReply: "Risposta automatica",
    enterToSend: "INVIO per inviare",
    settingsTitle: "Impostazioni",
    languageLabel: "Lingua interfaccia",
    languageAuto: "Auto (browser)",
    languageEnglish: "English",
    languageFrench: "FranÃ§ais",
    languageItalian: "Italiano",
    languageGerman: "Deutsch",
    languageSpanish: "EspaÃ±ol",
    languagePortugueseBr: "PortuguÃªs (Brasil)",
  },
  de: {
    threads: "Threads",
    createCharacter: "+ Charakter",
    importCharacter: "Charakter importieren",
    settings: "Einstellungen",
    personas: "Personas",
    loreBooks: "Lore-BÃ¼cher",
    shortcuts: "Shortcuts",
    back: "ZurÃ¼ck",
    previousPrompts: "Vorherige Prompts",
    send: "Senden",
    cancel: "Abbrechen",
    hideShortcuts: "Shortcuts ausblenden",
    showShortcuts: "Shortcuts anzeigen",
    autoReply: "Auto-Antwort",
    enterToSend: "ENTER zum Senden",
    settingsTitle: "Einstellungen",
    languageLabel: "Sprache",
    languageAuto: "Auto (Browser)",
    languageEnglish: "English",
    languageFrench: "FranÃ§ais",
    languageItalian: "Italiano",
    languageGerman: "Deutsch",
    languageSpanish: "EspaÃ±ol",
    languagePortugueseBr: "PortuguÃªs (Brasil)",
  },
  es: {
    threads: "Hilos",
    createCharacter: "+ Personaje",
    importCharacter: "Importar personaje",
    settings: "ConfiguraciÃ³n",
    personas: "Personas",
    loreBooks: "Libros de lore",
    shortcuts: "Atajos",
    back: "Volver",
    previousPrompts: "Prompts anteriores",
    send: "Enviar",
    cancel: "Cancelar",
    hideShortcuts: "Ocultar atajos",
    showShortcuts: "Mostrar atajos",
    autoReply: "Respuesta automÃ¡tica",
    enterToSend: "ENTER para enviar",
    settingsTitle: "ConfiguraciÃ³n",
    languageLabel: "Idioma de interfaz",
    languageAuto: "Auto (navegador)",
    languageEnglish: "English",
    languageFrench: "FranÃ§ais",
    languageItalian: "Italiano",
    languageGerman: "Deutsch",
    languageSpanish: "EspaÃ±ol",
    languagePortugueseBr: "PortuguÃªs (Brasil)",
  },
  "pt-BR": {
    threads: "Conversas",
    createCharacter: "+ Personagem",
    importCharacter: "Importar personagem",
    settings: "ConfiguraÃ§Ãµes",
    personas: "Personas",
    loreBooks: "Livros de lore",
    shortcuts: "Atalhos",
    back: "Voltar",
    previousPrompts: "Prompts anteriores",
    send: "Enviar",
    cancel: "Cancelar",
    hideShortcuts: "Ocultar atalhos",
    showShortcuts: "Mostrar atalhos",
    autoReply: "Resposta automÃ¡tica",
    enterToSend: "ENTER para enviar",
    settingsTitle: "ConfiguraÃ§Ãµes",
    languageLabel: "Idioma da interface",
    languageAuto: "AutomÃ¡tico (navegador)",
    languageEnglish: "English",
    languageFrench: "FranÃ§ais",
    languageItalian: "Italiano",
    languageGerman: "Deutsch",
    languageSpanish: "EspaÃ±ol",
    languagePortugueseBr: "PortuguÃªs (Brasil)",
  },
};
